// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wsn_keboo;

#nullable disable

namespace wsn_keboo.Migrations
{
    [DbContext(typeof(YourDbContext))]
    [Migration("20240121055958_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("wsn_keboo.Data.DataReceiveCom", b =>
                {
                    b.Property<int?>("IdEnumerate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rssi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Snr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Temperature")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("IdEnumerate");

                    b.ToTable("DataReceiveComs");
                });
#pragma warning restore 612, 618
        }
    }
}
